apiVersion: v1
kind: ConfigMap
metadata:
  name: recs-config
  namespace: recs
data:
  AWS_REGION: "us-west-2"
  SAGEMAKER_ENDPOINT: "recs-fm-endpoint"   # set to your real endpoint name, e.g. internal-ml-platform-fraud-endpoint
  SAGEMAKER_TIMEOUT_SECONDS: "5"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
