apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: platform
data:
  FRAUD_URL: "http://fraud.fraud.svc.cluster.local"
  RECS_URL: "http://recs.recs.svc.cluster.local"
  FORECAST_URL: "http://forecast.forecast.svc.cluster.local"
  HTTP_TIMEOUT_SECONDS: "2"
  SERVICE_VERSION: "1.0.0"
