apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Set images (CI will overwrite tags)
images:
  - name: FRAUD_IMAGE
    newName: FRAUD_IMAGE
    newTag: latest
  - name: RECS_IMAGE
    newName: RECS_IMAGE
    newTag: latest
  - name: FORECAST_IMAGE
    newName: FORECAST_IMAGE
    newTag: latest
  - name: GATEWAY_IMAGE
    newName: GATEWAY_IMAGE
    newTag: latest
  - name: DASHBOARD_IMAGE
    newName: DASHBOARD_IMAGE
    newTag: latest

patches:
  - path: patches/expose_loadbalancers.yaml
