name: Terraform (manual)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          role-session-name: gha-terraform
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init (platform)
        working-directory: terraform/platform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/platform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/platform
        run: terraform apply -auto-approve
